---
- name: config_openldap | configuring ldap
  template:
    src: "etc/ldap/ldap.conf.j2"
    dest: "/etc/ldap/ldap.conf"
    owner: root
    group: root
    mode: 0644

- name: config_openldap | configuring phpldapadmin
  template:
    src: "etc/phpldapadmin/config.php.j2"
    dest: "/etc/phpldapadmin/config.php"
    owner: root
    group: www-data
    mode: 0640

- name: config_openldap | creating database population config
  template:
    src: "etc/ldap/slapd.d/populate_content.ldif.j2"
    dest: "/etc/ldap/slapd.d/populate_content.ldif"
    owner: root
    group: root
    mode: 0640
    
